all:
	g++ -o test_mem_new_tcmalloc test_mem_new.cpp -O2 -I/home/ops/dev_tools/reactor_mini/include/ -I/home/ops/dev_tools/log4cplus-1.1.2/include /home/ops/dev_tools/reactor_mini/src/liblog4cplus.a -lpthread -std=c++11 -ltcmalloc_minimal

	g++ -o test_mem_new test_mem_new.cpp -O2 -I/home/ops/dev_tools/reactor_mini/include/ -I/home/ops/dev_tools/log4cplus-1.1.2/include /home/ops/dev_tools/reactor_mini/src/liblog4cplus.a -lpthread -std=c++11 -ltcmalloc_minimal

