all:
	g++ -o http_server *.cpp -I/home/ops/dev_tools/mqtt_server/include/ -I./ -I/home/ops/dev_tools/mqtt_server/include/msgpack  -std=c++11 -L/home/ops/dev_tools/mqtt_server/lib -lreactor -lcommon -llog4cplus  -lpthread
